# Generated by Django 4.2.20 on 2025-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thearchiveapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
