# Generated by Django 4.1.3 on 2024-02-06 01:11

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('thearchiveapi', '0002_alter_art_code_alter_art_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), name='unique_tag'),
        ),
    ]
