# Generated by Django 4.1.3 on 2024-02-06 01:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('thearchiveapi', '0003_alter_tag_category_tag_unique_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), name='unique_lower_category'),
        ),
    ]
