# Generated by Django 4.1.3 on 2025-10-19 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("thearchiveapi", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
