# Generated by Django 4.1.3 on 2025-10-26 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("thearchiveapi", "0004_subscriber_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="subscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
