# Generated by Django 4.1.3 on 2025-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thearchiveapi", "0005_subscriber_subscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
